name: Deploy to  CapRover

on:
  push:
    branches: ["-"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create deploy.tar for CapRover
        run: tar --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='deploy.tar' -cvf deploy.tar .

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAP_ROVER_SERVER }}"
          app: "${{ secrets.APP_NAME }}"
          token: "${{ secrets.APP_TOKEN_CAP_ROVER }}"
